"""empty message

Revision ID: 950fe9ea371a
Revises: 4bf54677967b
Create Date: 2019-02-14 15:26:59.948089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950fe9ea371a'
down_revision = '4bf54677967b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
